# Generated by Django 5.1.1 on 2024-09-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0004_article_is_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
