# Generated by Django 5.1.1 on 2024-09-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0005_article_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/word_files/'),
        ),
    ]
