# Generated by Django 5.1.1 on 2024-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0009_rename_url_advertisment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(upload_to='ads/photos/'),
        ),
    ]
