# Generated by Django 5.1.1 on 2024-10-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0010_alter_advertisment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
    ]
