# Generated by Django 5.1.1 on 2024-10-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0013_comment_creator_comment_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_of_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
