# Generated by Django 5.1.1 on 2024-11-15 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0016_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_viewd',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
