# Generated by Django 5.1.1 on 2024-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressApp', '0018_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
